name: Static Check

on: [pull_request]

env:
  CPPCHECK_PATH: ${{ github.workspace }}/cppcheck/build/bin/cppcheck

jobs:
    check:
      runs-on: ubuntu-22.04
      name: Run static check on patch series (PR)
      steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Download Astyle
        uses: carlosperate/download-file-action@v2
        id: download-astyle
        with:
          file-url: 'https://sourceforge.net/projects/astyle/files/astyle/astyle%203.0/astyle_3.0_linux.tar.gz'
          location: './astyle'

      - name: Print the file path (astyle.tar.gz)
        run: echo "The file was downloaded to ${{ steps.download-astyle.outputs.file-path }}"

      - name: Build Astyle
        run: |
          ls -l
          cd astyle
          ls -l
          tar -zxvf astyle_3.0_linux.tar.gz
          ls -l
          cd astyle/build/gcc
          make
          make install
          astyle -h
          astyle --version
      
      - name: Build Cppcheck
        run: |
          git clone https://github.com/danmar/cppcheck.git
          cd cppcheck
          git checkout 2.9
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ./bin/cppcheck --version

      - name: Static Check
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          astyle --version
          echo "${ALL_CHANGED_FILES}"
          python3 -u ./scripts/ci/static_check.py

